baseURL = "/"
disqusShortname = ""
languageCode = "en"
paginate = 10
summaryLength = "20"
theme = "hargo-hugo"
title = "Glam Bits | Fashion is a way of life, live it, feel it, embrace it."
[[menu.footer]]
URL = "contact"
name = "Contact"
weight = 4
[[menu.footer]]
URL = "terms-conditions"
name = "Terms & Conditions"
weight = 3
[[menu.footer]]
URL = "about"
name = "About"
weight = 2
[[menu.footer]]
URL = "products"
name = "Products"
weight = 1

[[menu.main]]
URL = "contact"
name = "Contact"
weight = 3
[[menu.main]]
URL = "about"
name = "About"
weight = 2
[[menu.main]]
URL = "products"
name = "Products"
weight = 1
    [[menu.main]]
    parent = "Products"
    name = "Plus Size"
    url = "plus-size"
    weight = 1
    [[menu.main]]
    parent = "Products"
    name = "Regular Size"
    url = "regular-size"
    weight = 2
    [[menu.main]]
    parent = "Products"
    name = "Shoes"
    url = "shoes"
    weight = 3
    [[menu.main]]
    parent = "Products"
    name = "Accessories"
    url = "accessories"
    weight = 4
[params]
author = "Kerrisha John"
copyright = "Copyright &copy; 2021 [Glam Bit](https://glambit.web.app/) All Rights Reserved. Website by [Kerrisha John](#)."
currencySymbol = "$"
description = "Fashion is a way of life, live it, feel it, embrace it."
email = "Info@glambits.com"
gmapAPI = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
googleAnalitycsID = "212952880"
home = "Home"
location = "Dhaka, Bangladedsh"
logo = "images/logo1.png"
mapLatitude = "12.051255"
mapLongitude = "-61.753218"
mapMarker = "images/marker.png"
mobile = "1(473)-415-0999"
snipcartApiKey = "M2E5YjA3NjMtYzRiYS00YzVjLWEyYWYtNDY5ZDI0OWZhYjg5"
[params.contact]
formAction = "#"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"
[params.preloader]
enable = true
preloader = ""
[params.rating]
enable = true
publicKey = "811cf0927332bf51f2e12f84608594ac"
websiteID = "444334"
[[params.social]]
icon = "ti-facebook"
link = "#"
[[params.social]]
icon = "ti-twitter-alt"
link = "#"
[[params.social]]
icon = "ti-youtube"
link = "#"
[[params.social]]
icon = "ti-instagram"
link = "https://www.instagram.com/glam_bits_boutique/"
[[params.social]]
icon = "ti-pinterest"
link = "#"
